apiVersion: apps/v1
kind: Deployment
metadata:
  name: brokerage-forex-backend
  namespace: brokerage-forex
spec:
  replicas: 1

  selector:
    matchLabels:
      app: brokerage-forex-backend

  template:
    metadata:
      labels:
        app: brokerage-forex-backend

    spec:
      containers:
        - name: backend

          image: docker.io/library/brokerage-forex-backend:k8s-v1

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 4030
              protocol: TCP

          envFrom:
            - secretRef:
                name: brokerage-forex-backend-secret

          readinessProbe:
            httpGet:
              path: /health
              port: 4030
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 4030
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 512Mi
