apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: brokerage-forex-frontend-pdb
  namespace: brokerage-forex
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: brokerage-forex-frontend
